connection/urls.py
from django.urls import path

from . import views

app_name = 'connection'
urlpatterns = [
    path('auth/', views.auth, name='auth'),
    
    path('auth/<str:username>/', views.user, name='user'),
    
    path('auth/<str:username>/<int:connection_id>/', views.detail, name='detail'),
    
    path('auth/<str:username>/<int:connection_id>/results/', views.results, name='results'),
]



""" 
    path('<int:connection_id>/', views.detail, name='detail'),


    
"""

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('connection/', include('connection.urls')),
    path('admin/', admin.site.urls),
]

connection/models.py
from django.db import models


class Connection(models.Model):
    host = models.CharField(max_length=200)
    backend = models.CharField(max_length=200)
    service = models.CharField(max_length=200)
    user = models.CharField(max_length=200)
    password  = models.CharField(max_length=200)
    verify_ssl = models.BooleanField(max_length=200)
    port = models.IntegerField()
    
    date = models.DateField()
    
    def __str__(self):
        return self.host + " " + self.backend + " " + self.service + " " +  str(self.port) + " " + str(self.date)
   
    @classmethod
    def get_default_pk(cls):
        return 1
        
        
class UserConnection(models.Model):
    username = models.CharField(max_length=200)
    connection =  models.ForeignKey(to=Connection, on_delete=models.CASCADE, default=Connection.get_default_pk)
    date = models.DateField()
    
    def __str__(self):
        return self.username + " " + str(self.connection) + " " + str(self.date)
        
        
class NodePassword(models.Model):
    nodename = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    connection =  models.ForeignKey(to=Connection, on_delete=models.CASCADE, default=Connection.get_default_pk)
    date = models.DateField()
    
    def __str__(self):
        return self.nodename + " " + str(self.password) + " " + str(self.connection) + " " + str(self.date)

connection/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone

from proxmoxer import ProxmoxAPI
from django.shortcuts import render

from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required

from subprocess import call, Popen

import time
import os
import stat

from .models import Connection, UserConnection, NodePassword

import logging


logger = logging.getLogger(__name__)
proxmox = None
proxmox_connection_id = None


def toggle_virt(virt_id, node_name, cls): #toggle start/stop of a container or virtual machine
    logger.warning("toggle")
    logger.warning(virt_id)
    logger.warning(node_name)
    logger.warning(cls)
    cls_system = "lxc" if cls == "ct" else "qemu"
    
    global proxmox
    for node in proxmox.nodes.get(): #fornow, for cycle is just to get status 
    	if node['node'] != node_name:
    		continue
    	if cls_system == "lxc":
    		for vm in proxmox.nodes(node['node']).lxc.get():
    			if int(vm['vmid']) == int(virt_id):
    				toggled_status = "start" if vm['status'] == "stopped" else "stop"
    				post_string = f"nodes/{node['node']}/{cls_system}/{virt_id}/status/{toggled_status}"
    				proxmox.post(post_string)
    	else:		
    		for vm in proxmox.nodes(node['node']).qemu.get():
    			if int(vm['vmid']) == int(virt_id):
    				toggled_status = "start" if vm['status'] == "stopped" else "stop"
    				post_string = f"nodes/{node['node']}/{cls_system}/{virt_id}/status/{toggled_status}"
    				proxmox.post(post_string)
	
def delete_virt(virt_id, node_name, cls): #delete a container or virtual machine
    logger.warning("delete")
    logger.warning(virt_id)
    logger.warning(node_name)
    cls_system = "lxc" if cls == "ct" else "qemu"
    
    global proxmox
    proxmox.delete(f"nodes/{node_name}/{cls_system}/{virt_id}")
        		
def create_container(request, connection_id):
    node_name = request.POST['nodename']
    
    vmid = request.POST['vmid']
    ostemplate = request.POST['ostemplate']
    hostname = request.POST['hostname']
    storage = request.POST['storage']    
    cores = request.POST['cores']
    memory = request.POST['memory']
    swap = request.POST['swap']
    net0 = request.POST['net0']
    password = request.POST['password']
    
    for node in proxmox.nodes.get():
        if node['node'] == node_name:
            proxmox.nodes(node['node']).lxc.create(
                vmid=vmid,
                ostemplate=ostemplate,
                hostname=hostname,
                storage=storage,
                cores=cores,
                memory=memory,
                swap=swap,
                net0=net0,
                password=password)

def create_vm(request, connection_id):
    node_name = request.POST['nodename']
    vmid = request.POST['vmid']
    proxmox.nodes(node_name).qemu.create(vmid=vmid)

def download_template(request, connection_id):
	node_name = request.POST['nodename']
	storage = request.POST['storage']
	download_url = request.POST['template_url']
	
	post_string = f"nodes/{node_name}/storage/{storage}/{download_url}"
	
	proxmox.post(post_string)
	
def parse_id_node(post_key, letter):
	print("PARSE_ID")
	print(post_key)
	str_id = post_key[: post_key.find(letter)]
	str_node = post_key[post_key.find(letter) + 1:][:-2]
	str_class = post_key[-2] + post_key[-1]
	return str_id, str_node, str_class


def getIpsDict(nodename, password, connection_id):
	host = Connection.objects.get(pk=connection_id).host

	unix_script = f"sshpass -p {password} ssh -o StrictHostKeyChecking=no root@{host} 'lxc-ls -f' >ips.txt"
	print(unix_script)
	temp_file = open("temp_file.sh", "w")
	temp_file.write(unix_script)
	temp_file.close()
	
	st = os.stat('temp_file.sh')
	os.chmod('temp_file.sh', st.st_mode | stat.S_IEXEC)
	
	rc = Popen("./temp_file.sh", shell = True)
	
	print(host)
	print(password)
	
	# wait ips to write down
	time.sleep(1)
	rc2 = call("pwd")
	ips_file = open("ips.txt", 'r')
	lines = ips_file.readlines()
	print(lines)
	return_dict = {}
	for line in lines[1:]:
		nl = line.split()
		print(nl[0], nl[4], nl[5])
		return_dict[nl[0]] = nl[4] if nl[4] != "-" else nl[5]
		logger.warning("container checked")

	logger.warning(str(return_dict))
	return return_dict

@login_required
def results(request, username, connection_id):    	   	     
    logger.warning("results")
    if request.method == "POST":
    	logger.warning("POST")
    	logger.warning(str(request.POST.keys()))
	
    	if "Refresh" in request.POST.keys():
   	   return HttpResponseRedirect(reverse('connection:results', args=(username, connection_id)))
    	if "Create ct" in request.POST.keys():
    	   create_container(request, connection_id)
    	   return HttpResponseRedirect(reverse('connection:results', args=(username, connection_id)))
    	if "Create vm" in request.POST.keys():
    	   create_vm(request, connection_id)
    	   return HttpResponseRedirect(reverse('connection:results', args=(username, connection_id)))
    	if "template_url" in request.POST.keys():
    	   logger.warning("template_url")
    	   download_template(request, connection_id)
    	   
    	   return HttpResponseRedirect(reverse('connection:results', args=(username, connection_id)))
    	virt_id = None
    	for k in request.POST.keys():
    		if (k[0] == 's'):
    			virt_id, node_name, cls = parse_id_node(k[1:], 's')
    			if virt_id is not None:
    				toggle_virt(virt_id, node_name, cls)
    			break
    		elif (k[0] == 'd'):
    			virt_id, node_name, cls = parse_id_node(k[1:], 'd')
    			if virt_id is not None:
    				delete_virt(virt_id, node_name, cls)
    			break
    	return HttpResponseRedirect(reverse('connection:results', args=(username, connection_id)))
    
    global proxmox
    res = "Connection id:"
    global proxmox_connection_id
    res += str(proxmox_connection_id)
    virts = []
    for node in proxmox.nodes.get():
    	nodename = node['node']
    	password = NodePassword.objects.filter(nodename=nodename, connection=connection_id).values('password').first().get('password')
     	
    	ips_dict = getIpsDict(nodename, password, connection_id)

    	for vm in proxmox.nodes(node['node']).lxc.get():
        	virts.append((vm['vmid'], vm['name'], node['node'], vm['status'], ips_dict.get(str(vm['vmid'])), 'ct'))
        	
    	for vm in proxmox.nodes(node['node']).qemu.get():
        	virts.append((str(vm['vmid']), vm['name'], node['node'], vm['status'], ips_dict.get(str(vm['vmid'])), 'vm')) #str(vm['vmid']) vms go with int fsr 

    virts = list(sorted(virts))
   
    return render(request, 'connection/results.html', {'res': res, 'virts' : virts})

def connect(request, connection_id):
    global proxmox_connection_id
    proxmox_connection_id = connection_id
    
    current_connection = Connection.objects.get(pk=connection_id)
   
    host = current_connection.host
    backend = current_connection.backend
    service = current_connection.service
    user = current_connection.user
    password = current_connection.password
    verify_ssl = current_connection.verify_ssl
    port = current_connection.port
	
    global proxmox
    proxmox = ProxmoxAPI(
    host=host, backend=backend, service=service, user=user, password=password,
    verify_ssl=verify_ssl, port=port)

def create_connection(request): #unused
    host = request.POST['host']
    backend = request.POST['backend']
    service = request.POST['service']
    user = request.POST['user']
    password = request.POST['password']
    verify_ssl = "True" if request.POST['verify_ssl'] == "True" else "False"
    port = int(request.POST['port'])
    cur_date = timezone.now()
    
    new_connection = Connection(host=host,
    				 backend=backend,
    				 service=service, 
    				 user=user, 
    				 password=password,
    				 verify_ssl=verify_ssl,
    				 port=port, 
    				 date=cur_date)
    new_connection.save()

def auth(request):
    if request.method != "POST":
    	logger.warning("NOT POST")
    	return render(request, 'connection/auth.html')

    username = request.POST['login']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('connection:user', args=(username,)))
    return render(request, 'connefction/auth.html')

@login_required
def user(request, username): 
    if request.method == "POST":
    	logger.warning("POST")
    	logout(request)
    	return HttpResponseRedirect(reverse('connection:auth', args=()))
    	
    users_connection = UserConnection.objects.filter(username=username).values('connection')
    context = {'connections' :Connection.objects.filter(pk__in=users_connection).all(), 'username' : username}
    
    return render(request, 'connection/user.html', context) 

@login_required    
def detail(request, username, connection_id):
    if request.method == "POST":
    	connect(request, connection_id)
    	return HttpResponseRedirect(reverse('connection:results', args=(username,connection_id)))
    connection = get_object_or_404(Connection, pk=connection_id)
    return render(request, 'connection/detail.html', {'connection': connection})
    

connection/templates/connection/auth.html
<html>
  <head>
    <title>Authorization</title>
    <style>
      div {
        margin-bottom: 10px;
      }
      label {
        display: inline-block;
        width: 150px;
      }
    </style>
  </head>
  
<form method="post">
{% csrf_token %}
<fieldset>
	<label for="login"> Login: </label>
	<input type="text" id="login" name="login" value=""><br><br>
		<label for="login"> Password: </label>
	<input type="text" id="password" name="password" value=""><br><br>
	<input type="submit" value="Log in">
</fieldset>
</form>



</html>

connection/templates/connection/detail.html
{{ connection }}


<form method="post">
{% csrf_token %}
<div>
<input type="submit" value="Connect" method="post">
</div>
</form>

connection/templates/connection/index.html
<html>
  <head>
    <title>Connections</title>
    <style>
      div {
        margin-bottom: 10px;
      }
      label {
        display: inline-block;
        width: 150px;
      }
    </style>
  </head>
  
{% if latest_connection_list %}
    <p> List of connections: </p>
    <ul>
	{% for connection in latest_connection_list %}
		<li><a href="{% url 'connection:detail' connection.id %}">{{ connection }}</a></li>
	{% endfor %}
    </ul>
{% else %}
    <p>No connections are available.</p>
{% endif %}


<p> You can create new connection:</p>           

	
<form method="post">
{% csrf_token %}
<fieldset>
	<label for="host"> host: </label>
	<input type="text" id="host" name="host" value="192.168.122.104"><br><br>
	<label for="host"> backend: </label>
	<input type="text" id="backend" name="backend" value="https"><br><br>
	<label for="host"> service: </label>
	<input type="text" id="service" name="service" value="PVE"><br><br>
	<label for="host"> user: </label>
	<input type="text" id="user" name="user" value="api@pve"><br><br>
	<label for="host"> password: </label>
	<input type="text" id="password" name="password" value="11111"><br><br>
	<label for="host"> verify_ssl: </label>
	<input type="text" id="verify_ssl" name="verify_ssl" value="False"><br><br>
	<label for="host"> port: </label>
	<input type="text" id="port" name="port" value="8006"><br><br>
	<input type="submit" value="Create Connection">
</fieldset>
</form>
</html>

connection/templates/connection/results.html
<html>
  <head>
    <title>Containers and VMs</title>
    <style>
      div {
        margin-bottom: 10px;
      }
      label {
        display: inline-block;
        width: 150px;
      }
    </style>
  </head>
  
  
{{ res }}

<form method="post">
{% csrf_token %}
<input type="submit" name ="Refresh" value="Refresh">
</form>


{% for virt in virts  %}
	<div>
	 <p> id: {{ virt.0 }} </p>
	 <p> node name: {{ virt.2 }}  </p> 
	 <p> name: {{virt.1}}  </p> 
 	 <p> status: {{ virt.3 }}  </p>
 	 <p> ip: {{ virt.4 }}  </p>
 	 <p> class: {{virt.5}} </p>  
	</div>
	<form method="post">
	{% csrf_token %}
	<input type="submit"  name =s{{virt.0}}s{{virt.2}}{{virt.5}} value="Start/Stop">
	</form>
	
	<form method="post">
	{% csrf_token %}
	<input type="submit"  name =d{{virt.0}}d{{virt.2}}{{virt.5}} value="Delete">
	</form>

{% endfor %}


<form method="post">
{% csrf_token %}
<fieldset>
	<label for="nodename"> nodename: </label>
	<input type="text" id="nodename" name="nodename" value=""><br><br>
	<label for="storage"> storage: </label>
	<input type="text" id="storage" name="storage" value="local"><br><br>
	
	<label for="template_url"> template download url: </label>
	<input type="text" id="template_url" name="template_url" value=""><br><br>
</fieldset>
<input type="submit" name ="Download template" value="Download template">
</form>


<form method="post">
{% csrf_token %}
<fieldset>
	<label for="nodename"> nodename: </label>
	<input type="text" id="nodename" name="nodename" value=""><br><br>
	
	<label for="id"> id: </label>
	<input type="text" id="vmid" name="vmid" value=""><br><br>
	<label for="ostemplate"> ostemplate: </label>
	<input type="text" id="ostemplate" name="ostemplate" value="local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz"><br><br>
	<label for="hostname"> hostname: </label>
	<input type="text" id="hostname" name="hostname" value="hostname"><br><br>
	<label for="storage"> storage: </label>
	<input type="text" id="storage" name="storage" value="local-lvm"><br><br>
	
	<label for="cores"> cores: </label>
	<input type="text" id="cores" name="cores" value="2"><br><br>
	
	<label for="memory"> memory: </label>
	<input type="text" id="memory" name="memory" value="512"><br><br>
	
	<label for="swap"> swap: </label>
	<input type="text" id="swap" name="swap" value="512"><br><br>
	
	<label for="net0"> net0: </label>
	<input type="text" id="net0" name="net0" value="name=eth0,bridge=vmbr0,firewall=1,tag=425,ip=dhcp"><br><br>
	
	<label for="password"> password: </label>
	<input type="text" id="password" name="password" value=""><br><br>
	<input type="submit" name = "Create ct" value="Create container">
</fieldset>
</form>

<form method="post">
{% csrf_token %}
<fieldset>
	<label for="nodename"> nodename: </label>
	<input type="text" id="nodename" name="nodename" value=""><br><br>
	<label for="id"> id: </label>
	<input type="text" id="vmid" name="vmid" value=""><br><br>
	<input type="submit" name = "Create vm" value="Create vm">
</fieldset>
</form>

</html>

connection/templates/connection/user.html
<html>
  <head>
    <title>Connections</title>
    <style>
      div {
        margin-bottom: 10px;
      }
      label {
        display: inline-block;
        width: 150px;
      }
    </style>
  </head>

<form method="post">
{% csrf_token %}
	<input type="submit" value="Log out">
</form>

{% if connections %}
    <p> List of connections: </p>
    <ul>
	{% for connection in connections %}
		<li><a href="/connection/auth/{{username}}/{{connection.id}}/">{{ connection }}</a></li>
	{% endfor %}
    </ul>
{% else %}
    <p>No connections are available.</p>
{% endif %}





</html>